
export let BasePath = "http://95.78.174.41:8081/"
export let UsersListPath = BasePath + "users/"
export let RegistrationPath = UsersListPath + "registration/"
export let LoginPath = UsersListPath + "login/"
export let GetUserPath = BasePath + "profile/"
export let GetHouseHoldBooksPath = BasePath + "kozhuuns/household_books/"
export let AddHouseHoldBookPath = BasePath + "kozhuuns/household_books/create/"
export let GetBankBooksPath = BasePath + "kozhuuns/household_books/bank_books/"
export let AddBankBooksPath = BasePath + "kozhuuns/household_books/bank_books/create"
